---
# base.yml
#
# add dev user and configure base OS

- name: "install libselinux-python for ansible"
  yum: "name=libselinux-python"

# dev user
- name: add dev user
  user: name={{ dev_user }}
- name: add class user to sudoers
  lineinfile: "dest=/etc/sudoers line='{{ dev_user }} ALL=(ALL) NOPASSWD: ALL'"

- name: turn off swap
  sysctl: name=vm.swappiness value=0 ignoreerrors=yes

- name: increase native threads and open files
  template: src=templates/limits.conf dest=/etc/security/limits.conf

