---
# class-data.yml
#
# download class input data

- name: check if the data has already been downloaded
  stat: path=/tmp/nasdaq-dividends.tar.gz
  register: dividends_archive

- name: run load data script
  script: files/load-nasdaq-data.sh
  when: not dividends_archive.stat.exists

- name: check if the class sample data has already been downloaded
  tags: samples
  stat: path=/tmp/class-sample-data.zip
  register: sample_data_archive

- name: load data for class samples
  tags: samples
  script: files/load-class-sample-data.sh
  when: not sample_data_archive.stat.exists

- name: clone class hadoop samples
  tags: samples
  command: "svn co https://hadoop-course.googlecode.com/svn/trunk/JHU605.788/HadoopSamples"
  args:
    creates: "/home/{{ dev_user }}/HadoopSamples"

- name: set PLAY_AREA variable
  tags: samples
  copy: src=files/hadoop-samples.sh dest=/etc/profile.d/hadoop-samples.sh
  sudo: yes

