---
# class-data.yml
#
# download class input data

- name: check if the data has already been downloaded
  stat: path=/tmp/nasdaq-dividends.tar.gz
  register: dividends_archive

- name: run load data script
  script: files/load-nasdaq-data.sh
  when: not dividends_archive.stat.exists

