---
# hadoop-handlers.yml

- name: restart yarn
  service: "name={{ item }} state=restarted"
  with_items:
    - "hadoop-yarn-nodemanager"
    - "hadoop-yarn-resourcemanager"

- name: restart mapreduce
  service: "name=hadoop-mapreduce-historyserver state=restarted"

