---
# provision.yml

- name: base OS configuration
  hosts: all
  tasks:
    - include: base.yml
      tags: base
    - include: development.yml
      tags: development
    - include: hadoop.yml
      tags: hadoop
    - include: data.yml
      tags: data
  handlers:
    - include: hadoop-handlers.yml

